### ISSUE TITLE
Per 100k values may be incorrect

### ISSUE THREAD

**Issue by Dleau** [COVID19Tracking/covid-tracking-dash#3]
This is great work, well done. But take NY state, for instance. As of today, there have been `145,753` total tests conducted. Your plots report `7,493` total tests conducted per 100k NY residents. Some simple math, `(145,753 * 100,000) / 7,493`, puts the population of NY state at around 1.9M, when in reality, it should be around 19M. I believe the per 100k residents values you are reporting are actually per 1M residents.

**Comment by eric-czech** [comment]
Thanks! I had fat-fingered the coefficient (fix deployed).
